h3js/h3

.github/workflows/ci.yml, .gitignore, jest.config.js, package.json, src/app.ts, src/promisify.ts, src/types.ts, test/app.test.ts, test/basic.test.ts, test/lazy.test.ts, test/utils.test.ts, yarn.lock
=> test: add basic test suite

test/cookie.test.ts
I've added test code for useCookies, useCookie, setCookie.
test covered when empty or exists cookie.
test covered single cookie with name
test covered setCookie with response.
=> test: add tests for useCookies, useCookie, setCookie

src/app.ts
=> fix: return 'false' and 'null' values as JSON strings

src/app.ts, src/error.ts
resolves https://github.com/nuxt/framework/issues/1027
=> perf: minify json returned from `h3` handlers

src/types.ts, src/utils/body.ts
=> fix: add missing `PATCH` method to types

src/event.ts
=> fix(types): nullables object props for response

README.md
Add documentation about https://github.com/kevinmarrec/h3-typebox for JSON Schema Validation.
=> docs: add `h3-typebox` utils to readme

src/app.ts, src/error.ts, src/event.ts, src/event/event.ts, src/event/headers.ts, src/event/index.ts, src/event/response.ts, src/event/utils.ts, src/router.ts, src/types.ts, src/utils/body.ts, src/utils/cache.ts, src/utils/cookie.ts, src/utils/request.ts, src/utils/response.ts, tsconfig.json
https://github.com/unjs/h3/issues/81
See also https://github.com/nuxt/framework/issues/5718.
=> feat: add `H3Event`, `H3Response` and `H3Headers`

package.json
Seems redundant. 
And thank you for this beauty!
=> chore: only run tests once during release

README.md
Add documentation about https://github.com/wobsoriano/h3-zod for Schema Validation.
=> docs: add h3-zod utils to readme

src/utils/proxy.ts
=> fix: import type from correct location

README.md
=> docs: improve nightly release usage section

.github/workflows/autofix.yml
=> ci: use conventional commits for autofix

README.md
Added Valibot package to community packages
=> chore: add valibot to community packages

src/event/utils.ts
=> fix: make request and response types explicit

README.md
=> docs: add `@intlify/h3` to community packages

src/utils/request.ts, test/utils.test.ts
=> fix(getRequestIP): use first address of `x-forwarded-for` header

examples/nested-router.ts
=> docs: fix typo in examples

docs/content/2.concepts/2.event-handler.md
=> docs: update the event handler page

docs/content/1.getting-started/2.installation.md
=> docs: update installation page

docs/content/3.guides/validate-data.md
=> docs: create a validate data guide

docs/content/3.guides/handle-session.md
=> docs: create handle session guide

docs/content/2.concepts/1.app.md
=> docs: update app page

docs/1.guide/1.index.md
=> docs: fix typo in Getting Started ("what happened")

docs/1.guide/1.index.md
=> docs: fix 2 typos

docs/1.guide/4.event.md
This PR fixes a small typo in a code example for event.respondWith
=> docs: fix 1 typo in respondWith example

docs/1.guide/1.index.md
#660 
Change `as` to `a` in the second sentence of the tip on the quickstart section page
It makes the sentence clearer at a glance.
Resolves #660
=> docs: fix typos

docs/1.guide/4.event.md
Fix the code example
instead of `import { query } from "h3";`
Should be `import { getQuery } from "h3";`
=> docs: fix import example in 4.event.md

docs/4.examples/from-expressjs-to-h3.md
=> docs: remove unwanted `console.log`

docs/1.guide/2.event-handler.md
none
delete `[` before `eventHandler`
=> docs: typo

src/event/event.ts, src/router.ts
=> docs: remove unnecessary asterisks

docs/1.guide/2.event-handler.md
=> docs: remove extra space

docs/1.guide/2.event-handler.md
An useless bracket was on the page
=> docs: typo on Event Handler page

docs/2.utils/2.reponse.md, src/utils/response.ts
=> docs: add jsdoc example for response utils

docs/4.examples/handle-session.md
none
session config cookie is of type `CookieSerializeOptions` : 
https://github.com/unjs/cookie-es/blob/a3495860248b98e7015c9a3ade8c6c47ad3403df/src/types.ts#L14 
which does not include `name`
=> docs: fix session example

docs/1.guide/2.event-handler.md
Resolves #755
I just fixed a typo.
=> docs: fix typo

docs/1.guide/4.event.md, test/status.test.ts
=> chore: fix typos

docs/4.examples/from-expressjs-to-h3.md
=> docs: update mogen example to use `combined` log format

docs/3.adapters/3.plain.md
The imported function is different from the one being used in the test example.
=> docs: fix typo for plain adapter example

src/handler.ts, src/types/handler.ts, src/types/utils/static.ts, src/utils/proxy.ts, test/types.test-d.ts
Addresses a pending todo in anticipation of next major.
=> fix(types)!: default `body` types to `unknown`

docs/.config/docs.yaml
Text is capitalized like other titles for keeping consistency.
=> docs: capitalize text

src/utils/internal/object.ts
I think we can remove this comment having `TODO:` or `I guess` in the code like that. May be.
=> chore: remove comments

docs/1.guide/6.websocket.md
Server-Sent Events is written with hyphens (-) everywhere. I think Server-Sent Events is the right format with hyphens.
https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events
https://en.wikipedia.org/wiki/Server-sent_events
=> docs: tiny typo

MIGRATION.md
=> docs: fix casing

docs/1.guide/2.event-handler.md
=> docs(event handler): fix grammar

src/utils/request.ts
https://github.com/unjs/h3/blob/b337fe7c424a8e2986e5ecbc11a9e3f23dfd76f6/test/validate.test.ts#L21-L26
=> docs: update `getValidatedQuery` jsdocs

src/utils/body.ts
=> docs(readBody): mention CSRF risk in jsdocs

docs/1.guide/6.websocket.md, examples/_ws.ts, examples/websocket.ts, package.json, pnpm-lock.yaml, src/app.ts
support [crossws 0.3.x](https://github.com/unjs/crossws/releases/tag/v0.3.0)
Main change is we need to support new `resolve` signature.
=> feat: support crossws 0.3

docs/1.guide/4.event.md
=> docs: remove duplicate list

src/h3.ts
=> types: exclude `fetch` from `serve` options

docs/4.examples/handle-session.md
=> docs: make grammar improvements to session example

docs/1.guide/2.app.md
=> docs(app-instance): capitalize text

src/utils/cache.ts
resolves #562
Backport the fix to v1 (see #1033 for v2)
=> fix(cache): correct comparison in cache headers

docs/1.guide/3.handler.md
Following up on https://github.com/h3js/h3/pull/1032
=> docs: add description for `File` response

src/utils/internal/cookie.ts, test/cookie.test.ts
resolves #1037
This PR backports the fix to v1 from #1041(v2)
=> fix(setCookie): unique by `name`, `domain` and `path` only

src/h3.ts, src/utils/internal/iron-crypto.ts, src/utils/proxy.ts, tsconfig.json
=> chore: erasableSyntaxOnly

src/h3.ts
=> refactor: remove duplicate `get`

MIGRATION.md
=> docs: fix typo in withBase

docs/1.guide/4.event.md, src/event.ts, src/types/event.ts, test/event.test.ts
based on https://github.com/h3js/srvx/pull/81
=> feat: `event.waitUntil`

src/index.ts
=> build: export more types

docs/2.utils/99.community.md
Apitally is an API monitoring, analytics and request logging tool with official support for H3 v2 via a new plugin in the [open-source JS SDK](https://github.com/apitally/apitally-js).
Would love to see this featured in the Utils > Community section of the docs! 💛
=> docs: add apitally to community integrations

docs/1.guide/1.basics/2.routing.md
=> docs: fix route meta example

src/_deprecated.ts, test/body.test.ts, test/unit/package.test.ts
resolves https://github.com/h3js/h3/issues/1117
=> feat: add `readMultipartFormData` for backward compatibility

src/utils/proxy.ts
resolves https://github.com/h3js/h3/issues/1187
=> fix(proxy): fix proxy headers filter

docs/4.examples/serve-static-assets.md
typo corrected: reads instead of read
=> chore(examples): fix typo
