src/app.ts
=> feat: allow chaining use statements

package.json, yarn.lock
When I run with `yarn test` , It fails by @types/jest not found. After I add `@types/jest`, It works well.
<details>
<summary>Click to check error log</summary>
```
PS C:\Users\pcjpc\Documents\h3> npm run test
> h3@0.2.5 test C:\Users\pcjpc\Documents\h3
> yarn lint && jest
yarn run v1.22.10
$ eslint --ext ts .
Done in 2.76s.
FAIL  test/basic.test.ts       
● Test suite failed to run
test/basic.test.ts:5:1 - error TS2593: Cannot find name 'describe'. Do you need to install type definitions for a test runner? Try `npm i --save-dev @types/jest` or `npm i --sav
5 describe.skip('promisifyHandle', () => {
~~~~~~~~
test/basic.test.ts:6:3 - error TS2593: Cannot find name 'test'. Do you need to install type definitions for a test runner? Try `npm i --save-dev @types/jest` or `npm i --save-de
6 …
```
=> chore: add `@types/jest` to `devDependencies`

src/error.ts
Currently, when using Nuxt, the createError does not generate meaningful error messages if only `statusMessage` is provided (which I see is more commonly been used in the Nuxt code base)
I would think it could be better to serve `statusMessage` if `message` is not provided. Ideally, maybe we could have better format as ``` `${input.statusCode}: ${input.statusMessage}` ``` but I will leave it for discussions
=> fix: createError fallback to statusMessage

src/app.ts
resolves https://github.com/nuxt/framework/issues/2739
We should either not lowercase routes when adding - or we should lowercase them both on adding routes _and_ per-request. I think case sensitivity is a reasonable default, with the possibility (of course) of adding a custom `.match` per-route to allow case insensitivity.
=> fix: don't lowercase routes when normalizing layers

src/app.ts
resolves #48
This enables us to send a response for:
* boolean
* number
* bigint
We may wrongly return a response for functions & symbols. Though likely that's a user error rather than something h3 should check for.
=> fix: allow returning, number and boolean as well

.gitignore
.idea folder is used by the jetbrain IDE suite
=> chore: ignore .idea folder

src/app.ts, src/event.ts, src/index.ts
A bit of context: #73
This refactor, is starting point to move away from `(req, res)` signature to `(event)` format with utilities with minimum possible changes to both core and usage. event is still a simple function `{ req, res }`. 
Tests are untouched and handlers will be automatically upgraded with a wrapper to event format, unless directly opting in an using `defineEventHandler`. Still using a semver-minor to alert about potential behavior changes.
```js
// Keeps working
app.use((req, res) => 'Hello World!')
// Opt-in to new event format
import { defineEventHandler } from 'h3'
app.use(defineEventHandler(() => 'Hello World'))
```
=> feat!: opt-in using event format using `defineEventHandler`

jest.config.js, package.json
h3 was migrated to vitest but there's still a jest config file that isn't used as far as I could see
=> chore: remove jest.config.js 

src/event.ts
otherwise `res.req` is undefined
=> fix: initialise `res.req`

CHANGELOG.md
a link to the following emoji (😐) looks like it was accidentally pasted in-between the word "handler"
=> chore(CHANGELOG): remove link to emoji svg inside "handler"

src/event.ts
https://www.typescriptlang.org/play?#code/PTAEDsFMHcCgEtwBdICcBmBDAxpUApAZQHkA5YgIwCtJslQBvWUUAbQA8AuUAZyVUQBzALrciZAGqYANgFdIAblgBfBMjRZcBEqQCCqVJgCeoSOxTgAJj1D7DRgDzjSUuZAB8jUKthmADgD2qPRIRn54zq7yoAC8zKAAPrz8QvFJ4LIAthRoaaAUAQHSkJjgec6UNHTlOnbGsLAgoADCsgaQyLCh4aAA+pEy8g4AKjF8AuCCCRnZaAkFRSXgnjGgw4lrrMIbAEq0QZYO40IANGvuvuyBwaDdETpRkMTSlrF9A24O-Q+DHg2w2AC4D4oEwYh+bjeTBYYNAAHJjpM4Sd4hRuKwGKB0IVuAiUkjvMIVA0mgBRAxBAFAkFo7SSX7PV6raGg3GIwTI1HozHYgJs-EcwnEoA
The current type does not handle nested object/array correctly
Close #104
Edit: oh it conflicts with #105, feel free to pick one you prefer :)
=> fix(types): fix JSONValue type

src/event.ts
Simply exposes an `EventContext` interface for manual typing:
```ts
declare module 'h3' {
interface EventContext {
myProperty?: boolean
}
}
export {}
```
resolves #122
=> feat: add `H3EventContext` for augmentation

package.json
in node16/nodenext module mode of TyepScript 4.7+, If package has `exports` entry on package.json, needs "types" field in `exports.*` for find typings.
ref. https://devblogs.microsoft.com/typescript/announcing-typescript-4-7/
=> fix(pkg): add `types` to the exports

src/app.ts, src/error.ts
- Support `createError({ fatal: true })` and `createError({ unhandled: true })`.
- Always normalize unhandled errors in the app stack and add `unhandled` when it was thrown as a plain error.
=> feat(createError): support `fatal` and `unhandled`

src/utils/body.ts, src/utils/cookie.ts, src/utils/request.ts
`use*` prefix is usually used for composables with context. Using more semantic prefixes instead by deprecating old ones.
- `useRawBody` => `readRawBody`
- `useBody` => `readBody`
- `useCookies` => `parseCookies`
- `useCookie` => `getCookie`
- `useQuery` => `getQuery`
- `useMethod` => `getMethod`
=> refactor: deprecate utils with `use*` prefix

README.md, src/utils/request.ts, src/utils/response.ts, test/header.test.ts
resolves #147
I added the following 3 utility functions as @pi0 suggested:
- `getHeaders(event)` for request
- `getHeader(event, name)` for request
- `setHeader(event, name, value)`
In addition, I added a unit test for `appendHeader()` function.
---
Do we need to make `getHeaders` and `getHeader` available for response?
For your reference, Express.js provides such functions as methods on `req` and `res` objects (i.e. `req.get` and `res.get`), so it's obvious from what object the functions get headers.
There are 2 ways to provide same functionalities with normal functions.
One is to let users pass `event.req` or `event.res`:
- `getHeaders(event.req)` / `getHeader(event.req, name)`
- `getHeaders(event.res)` / `getHeader(event.res, name)`
But `event` may be an `IncomingMessage` so developers …
=> feat: add utilities for http headers

README.md, src/utils/request.ts, test/router.test.ts, test/utils.test.ts
Resolves #120 
I added `getRouterParams(event)` utility function.
I also added `useRouterParams(event)` for it to be aligned with other API until the next braking change (may be v1?).
=> feat: add utility for router params (#120)

src/app.ts
Currently we get two copies of error logs if we are logging them in a user-provided `onError` handler. Presumably it makes sense for user to log (or not) if they are providing their own error handler
=> fix: don not log errors when `onError` is provided

src/types.ts
The changes in PR #124 to make the `H3EventContext` extendable by userland types were insufficient to apply the type also to the `CompatibilityEvent`, which is the type of events for event handlers. I always got `context.user: any` when only declaring the context interface:
```ts
declare module 'h3' {
interface H3EventContext {
user: User,
}
}
```
Because `CompatibilityEvent` can also be an `IncomingMessage`, which extends the `CompatibilityRequestProps`, which in turn still declares an un-extendable `context: Record<string, any>`. This gives `CompatibilityEvent.context: H3EventContext | Record<string, any>`, which gives `any` for all properties, even if `H3EventContext` is typed.
=> fix: `context` type for `CompatibilityRequestProps`

src/app.ts, src/event/event.ts, src/types.ts, tsconfig.json
resolves #169
**Note**: By disabling `esModuleInterop`, we will now get the same errors as others do who are using this library without it enabled.
=> fix: use named type imports from `http`

src/utils/body.ts
This addresses the issues of #170 where a second read from the body in a different library causes the request to hang.
Changing this to use `Symbol.for()` will first check the global registry for the symbol before generating a new one. I assume this means that different registries will share the same Symbol for the body and correctly early out once processed.
=> fix(readBody, readRawBody): use global symbol

README.md, src/event/event.ts
https://github.com/unjs/nitro/issues/439
=> feat: add `writeEarlyHints` utility

package.json, pnpm-lock.yaml
Hey 👋 
This PR defines the `package.json` in `exports` so other tools (e.g. for benchmarking) can read meta info from it.
Further read: https://github.com/uuidjs/uuid/issues/444#issuecomment-630424195 and https://github.com/nodejs/node/issues/33460
=> build: add `package.json` to subpath exports

src/app.ts, src/router.ts, test/router.test.ts
Resolves #183
Make router created by `createRouter` a middleware by default. Meaning it will lt the app continue searching for other matching middleware registered after if not route matches. (if route matches but not method, it will still throw an error).
**BREAKING CHANGE:** Router middleware will not stop with 404 if no matches are found. Using new `createRouter({ preemptive: true })` previous behavior can be done to stop app middleware immediately.
=> fix(router): make router handler non preemtive by default

playground/index.ts, src/error.ts, test/error.test.ts
Resolves #187
As suggested by @maicss, HTTP agents and servers (edge, browser, curl, etc) already resolve to the correct corresponding message for each error code. We don't need to bundle a preset of them or add a rather misleading "Internal Server Error" to all thrown errors.
=> fix!: remove default `statusMessage` from errors

src/router.ts, test/router.test.ts
Resolves #190
Using `URL` to parse and and extract pathname splitting from query.
=> fix(router): parse url using `URL` for pathname

src/utils/response.ts
subsequent to previous implementation, https://github.com/nodejs/node/pull/44820 made format object-based. this pr aligns h3 with node's current implementation
before https://github.com/nodejs/node/pull/44874 is released, we also have to manually replace crossorigin attribute 🤦
=> feat(writeEarlyHints): handle object-format early hints

test/body.test.ts
Add a few more test cases around empty and non-present bodies for https://github.com/unjs/h3/issues/197.
Some of the tests are currently failing as readBody/readBodyRaw for a request with `Content-Type: 'text/plain'` and `body: ''`  return undefined now. Is this the expected behavior? #197 was about distinguishing empty vs non-present bodies, but both return undefined now.
=> chore: add more tests for empty and non-present  

src/error.ts
Support `status` and `statusText` for [Response](https://developer.mozilla.org/en-US/docs/Web/API/Response) compatibility
=> feat(createError): support `status` and `statusText`

README.md, src/utils/proxy.ts, test/proxy.test.ts
Resolves #224 (Thanks @P4sca1 for suggestion)
This PR adds a new `proxyRequest` utility built on top of `sendProxy` that proxies incoming request headers, body and method to target. (path is not rewritten)
=> feat: add `proxyRequest` util

README.md, src/app.ts, src/error.ts, src/event/event.ts, src/node.ts, src/router.ts, src/utils/body.ts, src/utils/cache.ts, src/utils/cookie.ts, src/utils/proxy.ts, src/utils/request.ts, src/utils/response.ts, src/utils/route.ts, test/app.test.ts, test/header.test.ts, test/utils.test.ts
Ref #73
Using soft deprecation to use `event.node.req` and `event.node.res` instead of `event.req` and `event.res` preparing users for next iterations.
A new `event.path` getter also added to make accessing to path easier. (used `path` instead of `url` to avoid confusing hostname inclusion)
=> refactor: move `event.req` and `event.res` to `event.node.*`

README.md
Resolves #236.
I replaced deprecated methods in README according to the commit dc8ee81799bf93148ef686b3434287858afdafa0.
I also searched the word `deprecated` in VS Code just in case, and consequently there seems to be no more deprecated methods in the code base.
=> docs: fix deprecated methods

src/router.ts
Resolves #255.
cc: @AaronSmithX
=> refactor(createRouter): deprecate misspelled `preemptive` option

src/utils/body.ts, test/body.test.ts
resolves https://github.com/unjs/h3/issues/275
Previously a valid url-encoded string with multiple entries for the same value was not properly parsed. This creates arrays in such cases; it still doesn't support advanced nested arrays like `qs` but handles this specification as expected.
=> fix(readBody): handle top-level arrays in url-encoded data

.eslintrc, README.md, package.json, playground/index.ts, pnpm-lock.yaml, src/types.ts, src/utils/index.ts, src/utils/session.ts
Resolves #58
This PR adds basic session support. Sessions are sealed (encrypted and signed with a private key) in cookies using [iron-webcrypto](https://github.com/brc-dd/iron-webcrypto) (thanks @brc-dd ❤️) and [uncrypto](https://github.com/unjs/uncrypto) to work out of with Node.js and other environments.
The encrypted session is carried over cookies, therefore no server storage is required for session support.
Multiple session support is also possible with this implementation and custom `name` option (default is `h3` and used for cookie name as well )
Default cookie options are secure, httpOnly with path of `/` (can be configured)
Exposed utils:
- `useSession`: Initializes session and returns an `{ data, id, update(val), clear() }` interface to manage session. Wrapping `getSession`, …
=> feat: session support

src/utils/cookie.ts
When calling `setCookie` in same event multiple times with same name, it will add multiple `set-cookie` header updates. while this works on browser this remove old headers instead.
=> fix(setCookie): override existing `set-cookie` header with same name

src/utils/proxy.ts
In node, when new response is manually constructed (unenv) `_data` is set and it will be consumed. This PR handles this situation using internal API.
=> fix(proxy): handle consumed responses

README.md, src/utils/proxy.ts
Add two new proxy utils:
- `fetchWithEvent`: A fetch wrapper that uses event's context and incoming headers to proxy
- `getProxyRequestHeaders`: Gey filtered headers from incoming header we can proxy
=> feat: `fetchWithEvent` and `getProxyRequestHeaders` utils

src/utils/proxy.ts
in case of having consumed body, it could be also a JSON object that needs handling from h3. Otherwise use default behavior.
Note: `sendProxy` should always be returned in an event handler!
=> fix(proxy): handle consumed json body

.gitignore, package.json
I applied the latest unjs template, where `lint:fix` npm script is available with which we can fix/format files.
I also enable ESLint cache to speed it up.
=> chore: improve `lint` npm script

src/utils/session.ts
``` ts
// before need `password`
await clearSession(event, {password: '...'})
//  after
await clearSession(event)
```
=> fix(clearSession): accept partial session config

src/utils/body.ts, src/utils/cookie.ts, test/body.test.ts, test/cookie.test.ts, test/utils.test.ts
The following methods are now obsolete but still used in comments and test descriptions. In this PR, I've replaced them with new ones.
ref: 56bfe0a dc8ee81
- `useRawBody` => `readRawBody`
- `useBody` => `readBody`
- `useCookies` => `parseCookies` ( already fixed by #314 )
- `useCookie` => `getCookie`
- `useQuery` => `getQuery`
- `useMethod` => `getMethod`
=> refactor: replace obsolete methods in comments / test descriptions

src/utils/session.ts
This PR fixes CI failure in `Run pnpm lint`:
```
Run pnpm lint
> h3@1.5.0 lint /home/runner/work/h3/h3
> eslint --cache --ext .ts,.js,.mjs,.cjs . && prettier -c src test playground
Checking formatting...
[warn] src/utils/session.ts
[warn] Code style issues found in the above file. Forgot to run Prettier?
 ELIFECYCLE  Command failed with exit code 1.
Error: Process completed with exit code 1.
```
=> refactor: fix lint error

src/utils/session.ts
Referring to the example in #315 
```js
const session = await useSession<{ ctr: number }>(event, { password: sessionPassword });
await session.update((data) => ({ ctr: Number(data.ctr || 0) + 2 }));
session.data.ctr // type hints is any
```
However, getSession().data contains the correct hints, so this should be a bug.
=> fix(useSession): add types for `data` property

README.md, src/utils/request.ts
Resolves #347
Resolves #306
Implementing [requrl](https://github.com/unjs/requrl) and [is-https](https://github.com/unjs/is-https) as `h3` built-in utils.
I had been initially thinking to expose it as `event.url` it has some DX improvements but also downside of not being able to tree-shake and also not reflecting `req.path` changes.
=> feat: `getRequestHost`, `getRequestProtocol` and `getRequestURL` utils

src/error.ts, src/utils/response.ts
It will break the response if we set any of these characters by accident (e.g. if a user includes in an error message).
Related: https://github.com/nuxt/nuxt/issues/14688
=> fix: sanitize `statusMessage` of disallowed chars

src/utils/response.ts
We now check if `code` exists, which is important if this util is being used just to set the statusMessage.
=> fix(setResponseStatus): mark `code` type as optional

README.md
This pull request addresses an issue with the README.md file, specifically a missing closing parentheses on lines 101 and 124 of the `More app usage examples` section. The missing parentheses caused confusion for users attempting to copy said code and resulted in errors when running the code.
To fix this issue, I have added the missing closing parentheses to the lines in question.
=> fix: missing parentheses on README.md

src/utils/body.ts, test/body.test.ts
- Closes #363
I'm not sure if this implementation is enough. For my use-case in [nuxt-api-party](https://nuxt-api-party.jhnn.dev/):
```ts
// https://github.com/johannschopplich/nuxt-api-party/blob/main/src/runtime/server.ts#L26
let _body = await readBody<EndpointFetchOptions>(event)
// Inconsistent `readBody` behavior in some Nitro presets
// https://github.com/unjs/nitro/issues/912
if (Buffer.isBuffer(_body))
_body = destr((_body as Buffer).toString())
```
… this change fixed handling `Buffer` requests, e.g. when sending POST requests in a Cloudflare Nitro worker.
=> fix(readBody, readRawBody): handle raw body as buffer

src/utils/request.ts
Improve the return type of `getRouterParam` and `getRouterParams`. The latter's return type in particular is misleading especially when destructured:
And the implementation is simply returning the `event.context.params` with a fallback.
https://github.com/unjs/h3/blob/3e5f42748ab73102c1b9c2059fe8fa110e734363/src/utils/request.ts#L10-L13
Unless `event.context.params`, for some reason, can possibly have `sessions` and `params` in it?
=> fix(types): return type for get router parameter utils

.github/workflows/ci.yml, src/utils/proxy.ts
Proxy on Node.js >= 18, uses native `fetch` (which already splits `set-cookie` headers). Because of this, we need to merge/split all cookie headers and set it once otherwise (currently) only first cookie(s) will be added.
=> fix(proxy): split cookie headers properly with native node fetch

src/utils/proxy.ts, test/proxy.test.ts
Resolves #354 
This PR adds `onResponse` callback to `sendProxy` and `proxyRequest` utilities.
It accepts proxy `event` as argument which can be used to modify the response headers, cookies etc.:
```ts
return proxyRequest(event, target, {
onResponse(_event) {
setHeader(_event, 'foo', 'bar')
}
})
```
It can also be async:
```ts
return proxyRequest(event, target, {
async onResponse(_event) {
// some async stuff
}
})
```
=> feat(proxy): support `onResponse` callback

src/utils/body.ts, test/body.test.ts
- Closes #381 
- Related to 19d133d
Based in on [this](https://github.com/unjs/h3/commit/19d133d6a33ffb742713f4d83f00f555aeb83224#r109674536) where seems `unenv` already parsed the `body` to `Object` and when try to create a `Buffer` from it, in `nitro` Firebase preset, throw a error mentioned [here](https://github.com/unjs/h3/issues/381#issuecomment-1568943830)
```
TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received an instance of Object
```
This change check if `body` is a `Object` and converts to string before create a Buffer from it
=> fix(readRawBody): handle body as object

src/app.ts, src/router.ts, test/router.test.ts
Resolves #407. When `preemptive` router flag is enabled and an event handler is returning nothing, instead of showing a 404, we response empty string with 204 No Content gracefully.
This PR also makes slight fixes:
- Use `path` instead of `route` in error message of default app to distinguish errors
- Respect `preemptive` flag for when a route METHOD is not matching.
Note: For nitro, we need to enable flag to make this change effective.
=> fix(router): send 204 with empty string in preemptive mode instead of 404

src/utils/session.ts
Sometimes it may be necessary to customize the session ID.
for example, using something like `crypto.randomBytes(20).toString('base64url')`.
having a method available in the session configuration would be convenient.
=> feat(useSession): support custom session id generator

src/app.ts, src/error.ts, src/event/event.ts
Currently, we were directly depending on node `writableEnded` flag to determine if a response is ended or not. Sometimes user wants to takeover. By introducing more standard `event.handled` flag we can support it (first step will be possible with internal/experimental `_handled` flag when needed)
=> feat: support `event.handled` flag

src/utils/cache.ts, src/utils/proxy.ts, src/utils/response.ts
When event is handled, utils should early return and avoid calling `node.res.end`
=> fix(cache, proxy, response): avoid sending handled events

src/error.ts
Here are the changes I made to improve `H3Error`
- Added JSDoc comments for better code documentation.
- Fixed the incorrect property types in the class definition of H3Error.
- Fixed the incorrect property assignment in the constructor of H3Error.
- Added explicit return types for functions.
- Improved code formatting and consistency.
- Fixed a typo in the comment for the sendError function.
=> refactor: improve `H3Error`

src/utils/proxy.ts
Downstream we are wrongly typing `event.$fetch`. This is part of the fix.
=> fix(fetchWithEvent): allow customizing fetch impl type

README.md
- feat: add request and response helpers
- feat: add url utilities
- docs: document all builtins in readme
#420 
#423 
/!\ Careful this PR is against #427 , not main .
This update the readme to improve the readability and document the missing helpers.
=> docs: split readme into subsection and document missing helpers

src/utils/response.ts, test/app.test.ts
[](https://github.com/unjs/nitro/issues/1327)
This PR adds support for sending Web Streams for Node.js and for Worker environments (only via unenv+nitro). Also enables tests.
Users can directly return a web stream in an event handler.
Notes:
- Support for workers is experimental
- Node.js 18 is required for global `ReadableStream` (Node.js 16 does not support Web Streams)
=> feat: support web streams

src/event/event.ts, test/event.test.ts
#423, #73 
This PR adds `event.method` and `event.headers` support.
=> feat: add `event.method` and `event.headers`

src/app.ts
This is a minor refactor to improve app's return type handler to split if conditions. While working on several PRs, it was hard to maintained.
New refactor is also safer against edge conditions by making sure val is not falsy.
=> refactor(app:): split return type conditions

src/app.ts, src/utils/response.ts, test/app.test.ts
#73
This PR adds support for directly returning a web [Response](https://developer.mozilla.org/en-US/docs/Web/API/Response) object from event handlers, leveraging new streaming support for body! (#432)
It is also possible to explicitly use the newly exposed `sendWebResponse` utility.
**Note:** The rest is pretty much simple and implementation is already used for `event.respondWith` (by @danielroe ❤️). I am thinking in next steps, reuse same utility for `respondWith` as well and deprecating pollyfills we initially made due to runtime incompatibilities. (https://github.com/unjs/h3/pull/119) 
Also thanks to @Hebilicious for initial efforts in #395 to push for supporting native Responses ❤️
=> feat: web responses with streaming support

src/utils/response.ts
Resolves https://github.com/unjs/h3/issues/439
=> fix: split `set-cookie` value when handling web responses

src/utils/proxy.ts
When `proxyRequest` is used with different `method` (e.g. GET) defined in `fetchOptions`, the `body` is still filled and returns `Request with GET/HEAD method cannot have body.`
=> fix(proxy): respect `fetchOptions.method` over incoming request method

src/utils/response.ts
https://github.com/Hebilicious/authjs-nuxt/pull/38
It's possible that a Header object has multiple "set-cookie" headers.
=> fix: append `set-cookie` headers in web reponse

src/event/event.ts, src/utils/request.ts, test/event.test.ts
Related / Needed by #454
This adds `event.url` with a lazy initializer to access the request URL. 
By default, we use `getRequestURL` with default options (trusts `x-forwarded-proto` as a boolean and ignores `x-forwarded-host`)
=> feat(event): support `event.url`

src/event/event.ts, test/event.test.ts
#73, Needed by #454
This PR adds an experimental getter to the `event` object in order to access body via a lazy readable stream
=> feat(event): `event.body` with readable stream

src/event/event.ts, test/event.test.ts
#73 
This PR adds support for the lazy initialized `event.request` property that resolves to a standard [Web Request](https://developer.mozilla.org/en-US/docs/Web/API/Request).
**Note:** It is still **highly recommended** to prefer using top level event API (`event.{path,method,headers}`) as it has lower foot print and can be optimized per runtime platform.
Known issues: Node.js 16 does not supports ReadableStream as body for Request constructor
=> feat(event): `event.request` getter to access web request

src/utils/request.ts, src/utils/response.ts, test/header.test.ts
- feat: add request and response helpers
- feat: add url utilities
#420 
#423
This adds 7 new helpers.
=> feat: add `removeResponseHeader` and `clearResponseHeaders` utils

src/utils/proxy.ts
https://github.com/unjs/h3/issues/464
As discussed in https://github.com/unjs/h3/issues/464 and https://github.com/unjs/nitro/pull/1489.
`ProxyOptions` type updated to allow overriding the default value (`true`).
---
Is it **breaking change**?
I would say so, users may depend on error masking. This is not strictly a bug. Mandatory xkcd: https://xkcd.com/1172/
---
I personally dislike this solution a lot; if we allow freedom of passing fetch implementation, it should be up to the callee to configure the behavior of their implementation exactly as they like. If it's required to pass option to do so, they already can do so with `fetchOptions`.
Forcing `ignoreResponseError: true` is implicitly re-configuring non-default user-passed implementation. I think better approach is to allow the …
=> fix(proxy): transparently forward errors when passing ofetch

src/app.ts, src/event/event.ts, src/utils/request.ts, src/utils/route.ts
(failing tests against nuxt)
This PR adds backward compatibility to the changes in https://github.com/unjs/h3/pull/438 for `event.path` support. While we ideally could benefit from a single and normalized getter, it makes issues on edge cases when we are depending on legacy express like behavior (nuxt vite intention) to allow:
- Supporting not normalized routes with double slashes (`/module/@fs//...`)
- Supporting to manually modify event path by modifying `event.node.req.url` directly
- Allowing to use custom modified URL in same tick
Because of this, this PR reverts `event.path` behavior to _prefer_ future `_path` prop if exists and otherwise return (not normalized) `node.req.url` and also preserves `node.req.originalPath`
Also to avoid issues with same tick modification, app handler …
=> fix: keep backward compatibility with `event.node.req.url`

src/app.ts
This is an internal refactor to make future implementation changes easier for handling values directly returned in event handler as response.
=> refactor(app): extract handler returned response handling

src/utils/proxy.ts, test/proxy.test.ts
Resolves #450
When custom proxy headers are configured, they should override regardless of casing differences. This PR does this by introducing an internal util leveraging `Headers` object.
=> fix(proxy): merge overriden headers with different case

src/node.ts
When a custom `onError` is in place and it does not handle response, it can cause pending responses. This PR changes implementation to wait on `onError` and try to handle response by h3 directly if it is not handled yet.
=> fix(app): use default error handler if `onError` does not handles reponse

src/app.ts, src/error.ts, test/error.test.ts
Resolves #377
This PR improves H3Error class with a polyfill to support [v8 error cause](https://v8.dev/features/error-cause) universally. 
The `createError` wrapper also always provides input (or `input.cause` if provided) as cause so we can always access original error/object.
Another small fix: `onError` types fixed. It accepts an H3Error.
=> feat: preserve and make error cause accessable

src/event/event.ts, src/event/index.ts, src/event/polyfills/headers.ts, src/event/polyfills/response.ts, src/utils/response.ts
This PR deprecates legacy H3Request/H3Headers and uses new `sendWebResponse` utility for `event.respondWith` in order to reduce bundle size and uses latest/consistent response handling.
=> refactor(event): use `sendWebResponse` for `event.respondWith`

src/app.ts, test/app.test.ts
Resolves #447
This PR adds 3 new global hooks (options) `onRequest(event)`, `onBeforeResponse(event, { body })`, `onAfterResponse(event, { body }?)` useful for debugging and request/response interception.
Notes:
- All hooks support async but it is highly discouraged to avoid Promises and block all requests
- The `onResponse` hooks, only receive response with body when a handled directly returns it (not when using send* methods).
- Only one hook is supported in h3 level. Frameworks can leverage unjs/hookable to support more advanced integrations.
=> feat(app): `onRequest`, `onBeforeResponse` and `onAfterResponse` global hooks

src/utils/cookie.ts
No issue related, very small issue I spot by diving in the code.
The description was wrong on deleteCookie function
=> docs: fix `deleteCookie` description

src/event/utils.ts, src/types.ts, test/types.test-d.ts
https://github.com/unjs/h3/pull/417
resolves https://github.com/unjs/h3/issues/424
This supports object-syntax event handlers with the following syntax:
```ts
defineEventHandler({
handler: () => {},
before: [],
after: []
})
```
Helper validate functions need to be drafted that type-hint `event` and infer a return type. (I would suggest we also suggest `validate: { body: () => {}, query: () => {} }` which I think will be easier to directly get a type from as user can just return the validated body/query, which we can then flow through into rest of handlers.)
=> feat: object-syntax event handlers

src/event/event.ts
Using `console.log(event)` or directly returning it, leads to a complex and unreadable output like this:
This PR makes it stringified with method and FULL URL:
```
[PATCH] http://127.0.0.1:80/test
```
Note: `toJSON` is also usually expected to return a string and used by JSON.stringify (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toJSON)
=> feat(event): add default stringify with method and url for better dx

package.json, pnpm-lock.yaml, src/utils/response.ts, test/integrations.test.ts
=> feat: support react pipeable streams

src/adapters/web.ts
Reported by @Atinux > @danielroe 
This fixes the issue with null body responses in h3. Once nitro migrates to the web handler, it should fix all possible targets.
=> fix(web): use `null` for null body responses

README.md, src/adapters/node.ts, src/types.ts, src/utils/request.ts, test/utils.test.ts
https://github.com/unjs/h3/issues/272
We should make it convenient for users to get the client request ip while being able to opt-in to trust the x-forwarded-for header.
Currently, users are implementing themselves:
- https://github.com/Baroshem/nuxt-security/blob/main/src/runtime/server/middleware/rateLimiter.ts#L7C14-L7C30
- https://github.com/timb-103/nuxt-rate-limit/blob/master/src/runtime/server/utils/rate-limit.ts#L81
I'm also open to naming this `getClientIp` or `getRequestClientIp`.
This utility does open the door for trusting spoofable headers (see nuxt-security), sorting that is out of the scope of this utility, I'll open this as a seperate issue.
=> feat: util `getRequestIP` 

src/adapters/plain.ts, src/adapters/web.ts, src/event/event.ts, src/utils/body.ts, src/utils/proxy.ts, src/utils/request.ts, test/event.test.ts, test/plain.test.ts, test/utils.test.ts, test/web.test.ts
Before releasing h3 1.8, this PR makes sure we minimize new interface changes and chances of future possible breaking changes.
Meanwhile, I was trying new Web APIs, and figured it is so easy to shoot in the foot by runtime expensive getters such as `event.url` or `event.request` (did myself ironically!). Composable utils are a little bit more verbose to use but also easy to replace or deprecate.
Changes from the last RC:
- Move `event.rawBody` to `getRequestWebStream(event)`
- Move `event.request` to `toWebRequest(event)`
- Move top-level web context to `event.web?` (`WebEventContext = { request, url }`)
- Drop `event._originalPath` internal getter
- Drop `event._hasBody` internal getter
- Move `event.url` to `getRequestURL(event)`
- Fixed an unseen issue with `readRawBody` and `readBody` …
=> refactor: cleanup event interface

src/event/utils.ts, src/types.ts, test/types.test-d.ts
Context: Find most of DX issues while working on a example for https://github.com/unjs/h3/issues/501
This PR introduces two new define utils `defineRequestMidleware` and `defineResponseMiddleware` (with `RequestMiddleware` and `ResponseMiddleware`) types.
These utils are then used for event handlers with object syntax but can also used independently to define such hooks outside of the event handler in a composable way (imagine `compressionMiddleware` as util)
Also in order to keep consistency with global hook options and readability, the hooks are renamed from `before`/`after` to `onRequest`/`beforeResponse`.
Also we support non Array format for most consistency with top level
=> feat: `defineRequestMidleware`, `defineResponseMiddleware` and rename object synctax hooks

test/proxy.test.ts
https://github.com/unjs/nitro/issues/1605
This is a passing test to confirm the issue with proxy applying pretty-print to JSON is caused by downstream (nitro).
=> test(proxy): add additional test to make sure json response is sent as is

src/error.ts, src/event/event.ts, src/event/utils.ts, src/utils/body.ts, src/utils/internal/object.ts, src/utils/response.ts
Ref https://github.com/unjs/nitro/pull/1637
`in` operator expects the right hand to be an Object and can easily lead to edge case issues when we check something like `'foo' in 2` > `Uncaught TypeError: Cannot use 'in' operator to search for 'foo' in 2`.
This PR uses a small shared util for safer checks.
=> fix: use safe property checks

src/utils/request.ts
fix: add optional chain (.?) to event connection check in getRequestProtocol
A minor change, but essentially if event.node.req.connection is undefined ... we can't check for the encrypted boolean value, therefore an optional chain has been added.
=> fix(getRequestProtocol): conditionaly check `connection?.encrypted`

src/utils/response.ts, test/status.test.ts
Resolves #560
Resolves #560
setResponseStatus didn't work when no content was returned from eventHandler
- [ X] I have linked an issue or discussion.
=> fix(sendNoContent): preserve custom status code if already set

src/event/event.ts, src/event/utils.ts, src/utils/body.ts, src/utils/internal/object.ts, src/utils/internal/validate.ts, src/utils/route.ts
Add some more JSDocs for methods 👍🏻
=> docs: improve jsdocs

README.md
No related issues in this repository.
This PR is created based on https://github.com/unjs/website/issues/168#issuecomment-1791691182.
Pronunciation symbols are copied from Cambridge Dictionary:
- [h](https://dictionary.cambridge.org/dictionary/english-japanese/h)
- [three](https://dictionary.cambridge.org/dictionary/english-japanese/three)
=> docs: add package pronunciation

src/error.ts
This PR allows for typed data property of the `H3Error` class with an optional generic param defaulting to `any`, which in turn can be used to provide typed data property on the `err` returned by `createError` function.
=> types: add generics to `H3Error` data and `createError`

README.md, src/types.ts, src/utils/request.ts
Closes #516 
This PR adds a type-safe `getValidatedRouterParams` util.
=> feat: add `getValidatedRouterParams` util

src/utils/fingerprint.ts, src/utils/index.ts, src/utils/request.ts, test/utils.test.ts
closes #536
continuation of https://github.com/unjs/h3/pull/548
=> feat: add `getRequestFingerprint` util 

src/error.ts
Makes `isError` generic, hence removing the need to explictly annotate the return type of `createError`.
@pi0, shall we consider amending the default generic param for `DataT` from `any` to `unknown`, as per [this discussion](https://github.com/nuxt/nuxt/pull/24396#discussion_r1401272551)?
=> types: add generics to `isError` and update `DataT` default generic param

src/utils/internal/validate.ts, test/validate.test.ts
We were not forwarding the error from zod to the `data` property, making it impossible to get back the errors/issues from it.
Before:
After:
=> feat(validate): provide validate error in `data`

src/utils/body.ts
With `readRawBody` utility, we check `req.body` that can be provided from direct-fetch/unenv. (sadly) this conflicts with some runtimes (firebase) as I discovered which provides `req.body` as "parsed body".
Later we shall avoid depending on both and instead translate `rawBody` directly from higher-oder layers (user project or nitro preset entry for example) but this is a quick workaround for the situation.
=> fix(readRawBody): check `req.rawBody` before `req.body`

src/utils/response.ts
#542 
setResponseHeaders can also benefit from header autocompletion, so this PR adds it.
=> types(setResponseHeaders): add autocompletion for header names

src/utils/response.ts
https://github.com/unjs/h3/pull/542
resolves https://github.com/unjs/h3/issues/614
Currently, the record requires all keys to be set.
See: https://github.com/maevsi/maevsi/actions/runs/7428213670/job/20215223408
Adding `Partial` allows `value` to be `undefined` though. I guess the idea for undefined values would be to remove the corresponding header, but that change can be reverted of course!
=> fix(setResponseHeaders): fix types to allow partial header names

src/utils/body.ts
=> fix(getRequestWebStream): reuse buffered body if available

src/utils/response.ts
Since some properties were marked as deprecated and have the possibility of being removed in a major update, we shouldn't rely on them for types.
=> refactor: use `H3Event.node.res` for internal types

src/utils/response.ts, test/status.test.ts
- test: add failing test
- fix: avoid setting default `content-type` for responses with 304 status
resolves #603
=> fix: avoid setting default `content-type` for responses with 304 status

src/utils/proxy.ts
resolves https://github.com/nuxt/nuxt/issues/24742
resolves https://github.com/nuxt/nuxt/issues/24609
resolves https://github.com/nuxt/nuxt/issues/23539
This avoids proxying `accept` headers when fetching with event. Alternatively we could support an option via final argument to add additional headers to ignore, if you prefer.
=> fix(proxy): ignore incoming `accept` header

src/utils/static.ts, test/static.test.ts
This is a small fix to ensure `ETag` header is set before sending `304` response: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/304
> The response [...] must include the headers that would have been sent in an equivalent 200 OK response: Cache-Control, Content-Location, Date, ETag, Expires, and Vary.
=> fix(serveStatic): ensure `etag` header is set before sending 304 response

docs/4.examples/from-expressjs-to-h3.md
I think we can add a guide on using middleware with h3 for users accustomed to Express, which would facilitate their migration. 
tip: This is also the confusion I have encountered in actual use; I believe they might face similar issues as well. 🤣
=> docs(examples/from-expressjs-to-h3): add node middleware usage

docs/1.guide/1.index.md, docs/1.guide/2.app.md, docs/1.guide/2.event-handler.md, docs/1.guide/4.event.md, docs/1.guide/5.router.md, docs/3.adapters/2.web.md, docs/3.adapters/3.plain.md, docs/3.adapters/netlify.md, docs/4.examples/from-expressjs-to-h3.md, docs/4.examples/handle-cookie.md, docs/4.examples/handle-session.md, docs/4.examples/serve-static-assets.md, docs/4.examples/stream-response.md, docs/4.examples/validate-data.md
Resolves #664
As @Barbapapazes suggested, I replace `eventHandler` calls with `defineEventHandler` because the latter is more used.
At the same time, I also fixed the following points:
- Sort imports in alphabetical order
- In this point, it is better to fix #663 for consistency
- Fix typos
- Typo fixed by #658 is included in this PR too (so, it should be merged first)
- Refine sample codes
=> docs: refine function usages

src/app.ts, src/event/utils.ts, src/router.ts, src/types.ts, test/resolve.test.ts, test/status.test.ts
This PR exposes a new `app.resolve(path)` method that can be used to resolve an even handler matching path (method unspecified/get for now).
This API is useful to access handlers for new APIs such as WebSocket or accessing handler meta.
Resolver is async to allow lazy methods.
App, Nested App, Lazy handlers and Router are supported and tested.
=> feat: handler resolver

docs/2.utils/1.request.md, src/utils/body.ts
Update examples from the JSdoc annotations to improve IDE usage and documentation support.
=> docs: add jsdoc examples

docs/2.utils/98.advanced.md, src/utils/route.ts
This PR update the JSdocs annotations for the `route.ts` function to improve IDE support and documentation.
=> docs: update jsdocs example from route

docs/1.guide/6.websocket.md
=> Update 6.websocket.md: Yuu -> You

docs/1.guide/1.index.md
*n/a*
Case for named imports doesn't match.
=> docs: fix named import for toWebHandler in cdn example

docs/1.guide/5.router.md
const app = createApp();
const router = createRouter();
app.use(router;)
to 
const app = createApp();
const router = createRouter();
app.use(router)
=> Remove ; in app.use(router;) example createRouter()

docs/1.guide/4.event.md
=> docs: typo on event object page

docs/2.utils/1.request.md
Examples using Zod should be passing a callback to the `validated` reader functions instead of the schema object. This PR aligns the examples to be consistent with `readValidatedBody` (https://h3.unjs.io/utils/request#readvalidatedbodyevent-validate).
=> docs: fix zod example

docs/1.guide/4.event.md
Various spelling and grammar mistakes in the (Event Object)[https://h3.unjs.io/guide/event] documentation page.
=> docs: fix spelling and grammar mistakes in Event Object

docs/1.guide/2.event-handler.md
I believe `text/html` is the correct content-type
=> docs: fix typo for `text/html` content-type

docs/1.guide/4.event.md
=> docs: fix `respondWith` event object

src/utils/request.ts
Noticed that we missed to forward the options.
=> fix(getRequestUrl): forward opts to `getRequestProtocol`

docs/1.guide/4.event.md
**Reference:** #
There is `await readBody` inside `defineEventHandler`. It needs an async function.
=> docs: provide `async` for request body

docs/1.guide/2.event-handler.md, src/error.ts
#761
I have always been somewhat confused on how to initialize `createError`, either with a string or an object. Similarly, it was unclear at first which one to use to pass data to the client in an error thrown from the server. 
This is my first-ever open source contribution so I may not have configured the issue/pr or the contribution itself as needed. I'd love to hear if that is the case and I'll fix whatever is missing.
And just for context: @pi0 this is the pr I am opening per your suggestion over Twitter. Thanks for the nudge!
=> docs(error-handling): add string vs object errors and update `createError` jsdoc

src/adapters/plain.ts
Found from https://github.com/unjs/unenv/issues/274#issuecomment-2178545076 /cc @farnabaz 
For plain handler we were importing from unenv internals which are not same in upcoming unenv v2.
=> fix(plain): avoid import from unenv internals

src/adapters/node/_internal.ts, src/adapters/node/index.ts, src/adapters/node/utils.ts, src/adapters/web/_internal.ts, src/adapters/web/index.ts, src/adapters/web/utils.ts, src/deprecated.ts, src/error.ts, src/index.ts, src/types/web.ts
Related to #787
This PR introduces two new `callWithWebRequest(handler, request)` and `callWithPlainRequest(handler, request)` utils to allow directly emulating a web request on an app or event handler instance.
As part of reactors, `sendError` and `callNodeHandler/`callNodeListener` were removed.
=> feat!: `callWithWebRequest` and `callWithPlainRequest` utils

MIGRATION.md, docs/1.guide/6.websocket.md, docs/5.migration/0.index.md
=> docs: initial migration guide for v2

package.json, pnpm-lock.yaml, src/utils/cookie.ts, test/cookie.test.ts
resolves #705
Unique key generation was not restoring `maxAge` as the cookie parser was not restoring options (maxAge). 
Using new `parseSetCookie` from cookie-es 1.2 we can properly merge
=> fix(setCookie): properly merge unique set-cookie values

src/adapters/node/index.ts, src/adapters/node/internal/response.ts, src/adapters/web/event.ts, src/h3.ts, src/response.ts, src/types/event.ts, src/types/h3.ts, src/utils/internal/consts.ts, test/app.test.ts, test/bench/impl.ts, test/hooks.test.ts, test/proxy.test.ts, test/status.test.ts, test/web.test.ts
This PR improves raw web perf by ~10% by avoiding creating a `Headers` object in default/fast paths (finally `new Response()` does create one)
A new `event.response.setHeader` utility is introduced to allow setting headers on headers-init object via fast path (if `event.response.headers` is accessed, we fallback to full headers functionality)
This PR additionally makes behavior changes:
- `onError` is only called when error is throwing with `throw`. `return <error>` is normal response
- Returning a static string, does not sets HTML content type
- Default content type is `application/json; charset=utf-8` (normalized value of headers)
=> perf: improve response handling

package.json, pnpm-lock.yaml, src/types/utils/session.ts, src/utils/fingerprint.ts, src/utils/internal/iron-crypto.ts, src/utils/internal/session.ts, src/utils/session.ts, test/bench/bundle.test.ts, test/bench/session.ts, test/internal/iron-crypto.test.ts
Add a forked/inlined version of `iron-webcrypto` to allow better treeshaking and reduce external deps. 
i have added some additional internal cleanups as well including making sure all options are immutable. base64 utils replaced with cleaner implementation from [deno std lib](https://deno.land/std@0.224.0/encoding/base64url.ts?s=encodeBase64Url) (with more cleanups on top!)
uncrypto is still needed as a dep sadly because of Node.js 18 lacking global web crypto.
Session io (with ~1024 bytes of data) is up to 9x faster on node 18, ~%10 on node 22 and %15-30 faster on bun.
=> perf: improve session crypto

docs/1.guide/2.event-handler.md
Some properties are missing in the return json from docs.
The correct response for the first example of [Error Handling](https://h3.unjs.io/guide/event-handler#error-handling) is:
```json
{
"statusCode": 400,
"statusMessage": "Bad Request",
"stack": [],
"data": {
"field": "email"
}
}
```
Reference: Response in Hoppscotch:
=> docs: add detailed error response example

src/h3.ts, test/bench/bench.test.ts, test/bench/impl.ts, test/router.test.ts, test/web.test.ts
Running global and scoped middleware has a cost. This PR slightly reduces the cost by using promise chains.
Additional fixes:
- router context is now available for routed middleware
- global middleware match method if specified
=> perf: reduce the cost of global middleware

src/adapters/node/event.ts, src/adapters/web/event.ts, src/types/event.ts, test/bench/bundle.test.ts, test/bench/impl.ts
Creating a `URL` instance of `request.url` with full parsing (even though it is native!) has a cost.
This PR improves web performance by ~%10 on bun by introducing new `event.pathname` that in web APIs, if URL is not already parsed uses a faster method to extract pathname (used in critical path of event handling for matching routes)
=> perf: fast path for pathname for routing

package.json, pnpm-lock.yaml, src/adapters/node/event.ts, src/adapters/web/event.ts, src/h3.ts, src/types/event.ts, test/bench/impl.ts
Followup on #840
Creating a new `URL` for accessing query params has a cost too. This PR partially uses the search params segment of URL (which is already likely predicted by `pathname` fastpath too) 
---
Note: It adds `event.searchParams` mostly to be consistent with naming of web APIs and be similar to `event.url.searchParams`. DX-wise we might expose something more user friendly later or remove this before stable release aim of this PR is not DX but iterate faster on perf side of the story.
=> perf: fast path to access `searchParams`

src/adapters/node/internal/url.ts, src/utils/request.ts, test/_setup.ts, test/utils.test.ts
Followup on #844
Make `getRequestURL` consistent between adapters. Now it respects URL behavior for node, which that double slashes are preserved and backslashes normalized to slash but preserved when more than one is in one segment.
=> fix(getRequestURL): consistent behavior between node and web

package.json, pnpm-lock.yaml, src/utils/internal/encoding.ts, src/utils/internal/iron-crypto.ts, src/utils/internal/iterable.ts, test/_setup.ts, test/iterable.test.ts, test/unit/iron-crypto.test.ts, test/unit/iterable.test.ts
This PR fixes iterable compatibility with web targets that expect the stream chunks to be instances of Uint8 array (encoded text strings).
Previously it was only working on node (somehow!)
(PR also refactors encoding utils to save bundle on text encoder/decoder instances)
=> fix(iterable): always encode chunks

docs/2.utils/1.request.md, eslint.config.mjs, package.json, pnpm-lock.yaml, src/adapters/node/event.ts, src/adapters/web/event.ts, src/types/event.ts, src/utils/internal/encoding.ts, src/utils/internal/iron-crypto.ts, src/utils/internal/object.ts, src/utils/internal/query.ts, src/utils/request.ts, test/bench/impl.ts, test/sse.test.ts, test/unit/query.test.ts
Followup on #841
Parsing query params is costly and spec-compliant [URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams) (even with fast path optimization of #841) is not the fastest at least on Bun.
This PR tries another approach by providing `event.queryString` (fast path) and using an improved implementation of [anonrig/fast-querystring](https://github.com/anonrig/fast-querystring) via the existing `getQuery(event)` utility.
For simplicity, `event.searchParams` from #841 was renamed to `event.query`
Speedup is mainly benefiting Bun by ~%30 (latest node seems almost same perf) -- my guess is Bun is not optimized enough (for time being)
Bun:
Node.js:
=> perf: `event.query` and `getQuery` with faster impl

package.json, pnpm-lock.yaml, src/adapters/web/event.ts, src/h3.ts, src/response.ts, src/types/h3.ts, test/bench/bundle.test.ts, test/bench/impl.ts, test/hooks.test.ts
Normally when we return a value for h3, it tries to detect the content type and prepare a response/response-init. When users directly return a `Response` object (and have not preset any other headers or status/statusCode), we can go through a fast path optimization making handling  %3 to %6 faster.
---
But there is another part in the story. When h3 is combined with other web framework handlers that always return a `Response` object, we were blindly creating another `Response` object because it was working based on merging. 
By smarty reusing the same `Response` object, we can speed up to 2x (Bun) (%25 on Node) in performances.
---
This change also has the benefit that `onBeforeResponse` has access to the final prepared `Response` object instead of prepared `ResponseInit`
=> perf(web): fast path for returning `Response`

docs/2.utils/1.request.md
=> docs: add missing `parse` suffix for validation utils

src/utils/body.ts
=> fix(readRawBody): handle `URLSearchParams`

src/utils/static.ts
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Allow
> This header must be sent if the server responds with a 405 Method Not Allowed status code to indicate which request methods can be used.
=> fix(serveStatic): set `allow` header when responding with a `405`

src/utils/proxy.ts
Ref: https://github.com/nitrojs/nitro/issues/2880
Runtime's fetch client, might not support the encodings that the browser client supports.
The relevant issue was because Undici (Node.js) fetch does not support `zstd` but in general, it is an unsafe thing to pass through.
For performance, users can explicitly enable a supported `accept-encoding` to the server or we might later identify what runtime supports and set that instead (instead of the proxy incoming request)
=> fix(proxy): ignore incoming `accept-encoding` header

examples/body.ts, examples/errors.ts
=> chore(examples): fix typos

docs/2.utils/1.request.md, src/utils/request.ts
The functions `getValidatedQuery`and `getValidatedRouterParams` are async. This PR fixes the JSDoc examples.
=> docs(request): `getValidated*` utils are async

src/utils/internal/validate.ts, test/validate.test.ts
To be more friendly to catch third-party errors with `cause`
=> feat(validate): provide validate error in `cause`

src/utils/base.ts, test/integrations.test.ts
=> fix(withBase): update with `pathname` instead of `path`

docs/4.examples/stream-response.md
#849 fixed one of these in the `v1` branch, but the live site seems to be showing the `main` branch content.
=> docs: fix small typo in streaming docs

docs/2.utils/98.advanced.md, src/utils/proxy.ts
resolves nitrojs/nitro#2985
regression with https://github.com/unjs/h3/commit/d4f863f096cecea7b406301c4529da938dd1804c was that for fetching URLs with relative path (only valid for nitro direct-fetch), we were skipping `host` header.
- For external proxy, it makes sense to preserve the original host (previous fix)
- For local targets `/path` there is virtually no host, so inherit makes sense. (this fix)
This PR fixes `proxyRequest` (used by nitro proxy route rules) and `fetchWithEvent` (used by nitro `event.$fetch`)
=> fix(proxy): pass `host` for local targets

src/error.ts
`internal` is removed at https://github.com/unjs/h3/commit/b38d450e39101104333f33516d75869cd2427f9d#diff-39f1e030815f30ed52f7f86a69761ef60e22bbfd1521ac8d065e6d86a4bc8337L18
Should I send PR for v1 too?
https://github.com/unjs/h3/blob/v1/src/error.ts#L20
=> docs: fix jsdoc

src/error.ts
`internal` is removed at https://github.com/unjs/h3/commit/b38d450e39101104333f33516d75869cd2427f9d#diff-39f1e030815f30ed52f7f86a69761ef60e22bbfd1521ac8d065e6d86a4bc8337L13-R71
This pull request makes the same changes to v1 as #945
=> docs: fix jsdoc (v1)

docs/1.guide/2.event-handler.md
actually `example-node-middleware` does not exist. I have given a comment on it so that it provides clarity like this for "web-handler" (https://h3.unjs.io/guide/event-handler#converting-from-web-handlers).
=> docs(event-handler): provide clarity on package

docs/2.utils/98.advanced.md, src/utils/cors.ts
The handleCors example had a stray paren and the indentation made the code difficult to read and understand.
Resolves #957.
=> docs: fix syntax and indent in handleCors example

docs/1.guide/4.event.md, package.json, pnpm-lock.yaml, src/adapters/plain.ts
This PR migrates from `unenv` (for Workers support) to [`node-mock-http`](https://github.com/unjs/node-mock-http) which is extracted from codebase of unenv v1.
The reason for migration is that unenv v2 will have breaking changes for `node:http` (unjs/unenv#364) and ecosystem migration is not easy.
One temporarily downside is that this causes duplicate polyfills for Nitro users however nitro (v2) will also migrate.
One benefit of this new extracted package is that we can avoid polyfills for `node:buffer` and `node:events` in Node.js runtimes (using export conditions in `node-mock-http`)
=> feat: migrate from `unenv` v1 to `node-mock-http`

docs/2.utils/98.advanced.md, package.json, pnpm-lock.yaml, src/utils/cookie.ts, src/utils/internal/cookie.ts, test/cookie.test.ts
resolves #705 for h3 v1 (backporting #830)
> Unique key generation was not restoring maxAge as the cookie parser was not restoring options (maxAge).
> Using new parseSetCookie from cookie-es 1.2 we can properly merge
This PR also drops dependency on ohash v1
=> fix(setCookie): properly merge and dedup `set-cookie` header

src/h3.ts, src/response.ts, test/app.test.ts, test/bench/bundle.test.ts
This PR rewrites response handling logic to increase safety and consistency. 
`onError` and `onBeforeResponse` config hooks are guaranteed to always be called for 404 and other situations.
=> refactor: improve response and hooks handling

package.json
Module syntax detection is enabled by default in [Node.js v20.19.0](https://nodejs.org/en/blog/release/v20.19.0) and [Node.js v22.7.0](https://nodejs.org/en/blog/release/v22.7.0). But Node.js recommends to use `"type"`: `"module"` when it comes for ESM. Node.js doc says, Syntax detection should have no performance impact on CommonJS modules, but it incurs a slight performance penalty for ES modules; add "type": "module" to the nearest parent package.json file to eliminate the performance cost. (https://nodejs.org/en/blog/release/v20.19.0#module-syntax-detection-is-now-enabled-by-default) That's why I think we may add it in `package.json`.
=> build: add `type: "module"` to the package

eslint.config.mjs, src/utils/proxy.ts, test/proxy.test.ts
resolves #865
This backports the fix to v1. (see #1026 for v2)
If it's not needed, feel free to close it. ❤️
=> fix: handle `Headers` when merging proxy headers 

src/adapters.ts
Fixes #1039 
By resolving the stream piped to the response in the `callNodeHandler` fn, the issue described in the mentioned issue will be fixed.
=> fix(node): pass through piped stream

src/utils/cookie.ts, test/cookies.test.ts
resolves #1037
This PR uniquely identifies cookies by only three segments: "cookie-name, domain-value, and path-value" according to this spec: https://httpwg.org/specs/rfc6265.html#rfc.section.4.1.2
> If the user agent receives a new cookie with the same cookie-name, domain-value, and path-value as a cookie that it has already stored, the existing cookie is evicted and replaced with the new cookie. Notice that servers can delete cookies by sending the user agent a new cookie with an Expires attribute with a value in the past.
=> fix(setCookie): unique by `name`, `domain` and `path` only

src/utils/static.ts
Although it is not a security issue itself, if `statusMessage` used in HTML body unescaped, it can lead to security issues.
Alternatively we could use encoded id in message however it seems extra unnecessary information.
=> fix(serveStatic): omit decoded id from `statusMessage`

src/utils/internal/standard-schema.ts, src/utils/internal/validate.ts, test/validate.test.ts
Smaller rework of #964 (thanks @sandros94 ❤️ ) resolves #963 to support [standard schema](https://github.com/standard-schema/standard-schema) validators (zod, valibot, etc)
=> feat(validate): standard schema support

MIGRATION.md, src/handler.ts, src/index.ts, src/types/_utils.ts, src/types/h3.ts, src/types/handler.ts, src/utils/ws.ts, test/unit/package.test.ts, test/unit/types.test-d.ts
Remove legacy generic signature for event handler `<reponse>`.
Also removed object syntax. With new chainable middleware (#1065) we can support new `defineEventHandler(handler, { middleware: [...] })` / `app.*(handler, { ... })` to intercept before/after response and errors (in next PRs)
=> refactor: remove object syntax support and legacy types

docs/1.guide/3.handler.md, docs/1.guide/5.routing.md, src/h3.ts, src/handler.ts, src/types/h3.ts, src/types/handler.ts, test/middleware.test.ts
Follow-up on new chainable middleware #1065
This PR allows registering middleware like auth to be attached to registered event handlers.
Compared to global middleware, this kind of middleware is guaranteed to run in the scope of the registered event handler and also does not need to be globally filtered to be matched (which is more secure).
Register during definition:
```js
defineEventHandler((event) => {}, [auth]);
```
Register during registration:
```js
app.get("/edit", (event) => {}, [auth]);
```
=> feat: support attached middleware for handlers

docs/2.utils/98.advanced.md, src/utils/proxy.ts
resolves #825
resolves #709
related: #504
related: https://github.com/nitrojs/nitro/issues/3160
TODO:
=> feat(proxy): support `forwardHeaders` and `filterHeaders`

src/h3.ts, test/app.test.ts, test/router.test.ts
now you can add h3 routes with arabic letters.
=> fix(router): normalize added routes

examples/errors.mjs, src/error.ts, src/response.ts
When throwing response errors with `throw createError()`, any existing set headers with `event.res.headers` will be discarded (as they are meant to prepare for final normal response)
This PR adds support for `throw createError({ headers: {...} })`.
=> feat: error with custom headers

src/handler.ts, src/types/handler.ts, test/handler.test.ts, test/middleware.test.ts, test/unit/types.test-d.ts
Update: Adding back object syntax of h3 v1 with `defineEventHandler({ handler, middleware })`. It is safest bet to 1) keep backward compatibility 2) think more about proper order for shorthand overload of function (either B or C) in next betas.
---
Trying to find the best ergonomic API for `defineEventHandler` with middleware (see #1075)
General findings:
- A is often found best by first look and is progressive (optional last), but as the handler logic length increases, middleware becomes less visible. Also, it does not show the right order of execution.
- C, it is best to give a clearer/simpler API, but an array might be harder to infer types from
- B is a little less organized but has the benefits of C and might be better for types 
```js
defineEventHandler((event) => {
// [A: current] …
```
=> refactor: add back object syntax for `defineEventHandler`

src/adapters.ts, src/h3.ts, src/types/h3.ts
`app.fetch` in v2 accepts 3rd context param, which is not standard. Also can return non-promise values (because runtime fetch can handle it).
This PR moved it under `app._fetch`, making sure `app.fetch` strictly matches the standard `fetch` signature and behavior.
=> refactor: make `app.fetch` matching `fetch`

examples/handler-fetch.mjs, src/h3.ts, src/handler.ts, src/response.ts, src/types/handler.ts, test/bench/bundle.test.ts
Reuse existing composable internals to enable event handlers defined with `defineEventHandler` directly be a usable `.fetch`-able interface!
Thanks to initial inspiration from @productdevbook since he was asking how to just use the (value => Response) part of h3 ❤️ 
```js
import { defineEventHandler } from "h3"; // 5kB (2kB gzipped)
const log = (event) => {
console.log(`[${event.req.method}] ${event.req.url}`);
};
// ✔ Inferred Types: (event: H3Event<EventHandlerRequest>) => { hello: string; }
const handler = defineEventHandler({
// ✔ Request middleware
middleware: [log],
// ✔ Directly return a value or throw an error
handler: () => ({ hello: "world" }),
});
// ✔ compatible with .fetch API
// Use for teesting or integrate into any compatible framework and runtime!
// [GET] …
```
=> feat(defineEventHandler): support `.fetch` interface

docs/2.utils/98.advanced.md, src/utils/cors.ts, src/utils/internal/cors.ts, test/unit/cors.test.ts
=> fix(cors)!: doesn't return `access-control-allow-origin` header when origin is disallowed

src/utils/static.ts
I think we should check mtime first and then ETag. 
Because when generating ETag, we always need to read the file content and perform heavy CPU computations. 
In contrast, checking mtime only requires accessing the file's modification time metadata.
There are no breaking changes - just a logical order adjustment. 
It's a small change, but it dramatically improves service performance.
=> refactor(serveStatic): check mtime before etag

MIGRATION.md, docs/1.guide/1.basics/4.handler.md, docs/1.guide/1.basics/5.response.md, docs/2.utils/4.security.md, docs/99.blog/1.v1.8.md, examples/handler-fetch.mjs, examples/handler-obj.mjs, src/_deprecated.ts, src/handler.ts, src/index.ts, src/utils/auth.ts, src/utils/ws.ts, test/bench/bundle.test.ts, test/handler.test.ts, test/middleware.test.ts, test/unit/package.test.ts, test/unit/types.test-d.ts
Rename `defineEventHandler` to a shorter `defineHandler` for usage. (deprecated export exists for BW compat)
=> refactor: `defineEventHandler` => `defineHandler`

docs/1.guide/1.basics/1.lifecycle.md, docs/1.guide/900.api/1.h3.md, docs/99.blog/1.v1.8.md, examples/handler-obj.mjs, src/response.ts, src/types/h3.ts, test/_setup.ts, test/hooks.test.ts
Rename `onBeforeResponse` (global hook and middleware) to `onResponse`.
Reasons:
- More consistent with other hooks `onRequest`/`onError`
- Shorter
- Less confusing somehow because `onAfterResponse` does not makes any sense in web standards (there is `event.waitUntil` does goes _in parallel_ to and after response)
=> refactor: `onBeforeResponse` => `onResponse`

docs/1.guide/900.api/1.h3.md, eslint.config.mjs, examples/plugin.mjs, src/h3.ts, src/index.ts, src/types/h3.ts, test/unit/h3.test.ts, test/unit/package.test.ts
This PR adds a similar feature to srvx plugins. H3 plugins are essentially a function that hook to H3 app instance and can extend internals, such as adding new routes, global middleware or modifying class behavior for a declarative, reusable system (related to #1088)
Implementation is intentionally kept super minimal to avoid any overhead and maximise possibilities. We might add extendable hooks later to make plugins easier to implement.
**Example:** Logger plugin.
```js [plugin.mjs]
import { definePlugin } from "h3";
export const logger = (_options) =>
definePlugin((h3) => {
if (h3.config.debug) {
h3.use((req) => {
console.log(`[${req.method}] ${req.url}`);
});
}
});
```
```js [app.mjs]
import { H3 } from "h3";
new H3({ debug: true })
.register(logger())
.all("/**", () => "Hello!");
// …
```
=> feat:  plugins

docs/1.guide/1.basics/3.middleware.md, docs/1.guide/900.api/1.h3.md, docs/2.utils/9.more.md, examples/middleware.mjs, src/response.ts, src/types/h3.ts, src/utils/middleware.ts, test/hooks.test.ts
Use consistent argument types between global and middleware hooks for `onRequest`, `onResponse` and `onError`
This PR also improves middleware shortcuts to allow overriding error or response.
=> refactor: consistent hooks

MIGRATION.md
Fixes a small typo in the migration guide.
=> docs: fix typo `event.req` is instance of request

src/h3.ts, src/index.ts, src/types/h3.ts, test/bench/bundle.test.ts, test/unit/package.test.ts
This PR exposes `H3Core`, an abstract class without implementation for `_findRoute` to allow replacing the router.
Bundle size saving is medium (`7.4kB` core vs `9.6kB` with rou3), but the main benefit is giving better low-level control.
With this PR, we also expose `_routes: []` internal array useful for next steps, both accessing nested app route meta (#1111) and better sub-app (#1107) since we can "replay" route additions tothe  main app when mounting it.
=> feat: export `H3Core`

docs/1.guide/1.basics/7.nested-apps.md, docs/1.guide/900.api/1.h3.md
Add a dedicated "Nested Apps" section for `app.mount` usage (cont. #1129)
=> docs: add nested apps section

src/response.ts
Resolves #1132
Bun has a very strange implementation of `Blob` where `'name' in new Blob()` is true, making H3 to wrongly detect Blobs ad downloadable files.
This PR makes h3 more secure by making sure only to add the name if it has a value.
=> fix(response): only add `content-disposition` for `File` with name

docs/2.utils/5.proxy.md, src/utils/internal/proxy.ts, src/utils/proxy.ts, test/proxy.test.ts
v1 proxy utils depended on specific behavior for Nitro and ofetch compatibility for direct fetch.
Since in v2 we are fully based on web standards, and with the addition of `event.app.fetch` (#1139) which allows direct fetch, we can fully switch to runtime natives!
=> feat(proxy): use native `fetch` + `event.app.fetch`

src/error.ts, test/body.test.ts
Bundlers (and runtimes) can sometimes rename class name for `HTTPError` which makes it unreliable for checking.
This PR adds `HTTPError.name: "HTTPError"` also safer `HTTPError.isError` check.
=> fix: safer `HTTPError` check

src/handler.ts, src/utils/route.ts
Experimental `defineValidatedHandler` (#1097) should accept all possible `EventHandlerObject` props (typed superset)
This PR fixes issue that `.meta` was ignored.
=> fix(defineValidatedHandler): accept all `EventHandlerObject` props

src/handler.ts, src/utils/internal/validate.ts, src/utils/route.ts, test/handler.test.ts, test/route.test.ts, test/unit/types.test-d.ts
This PR refactors experimental `defineValidatedHandler` (#1097) and `defineRoute` (#1143) to use a more clear `validate: {}` namespace in definition.
=> refactor!(defineValidatedHandler, defineRoute): use `validate: {}` namespace

docs/2.utils/2.response.md, src/utils/response.ts
resolves #1170
I chose to explicitly pass in the event rather than do it implicitly like this
```js
app.get("/", noContent);
```
in case there are [future signature changes](https://jakearchibald.com/2021/function-callback-risks/)
=> docs: fix example for noContent util

src/utils/route.ts
This PR fixes the `meta` type inside `RouteDefinition` to use the `H3RouteMeta`. This aligns it with the rest of the meta properties and enables consistent type augmentation across all route definitions.
=> fix: use `H3RouteMeta` in `RouteDefinition` types

src/adapters.ts, src/event.ts, src/types/context.ts, test/middleware.test.ts
This PR adds support for `ServerRequest.context` to be automatically used for `H3Event.context` instead of initiating another ref for broader compatibility.
Also now `h3.H3EventContext` inherits `srvxServerRequestContext` for sharing types.
=> feat: inherit `req.context` and `ServerRequestContext` types

src/h3.ts, src/handler.ts, src/index.ts, src/types/h3.ts, src/types/handler.ts, test/app.test.ts, test/handler.test.ts
H3 by default supports `(event: H3Event) => any` handler format.
For better external compatibility, we have introduced `app.mount(<base>, <fetchable>)` where it is possible to mount an external framework like Elysia or Hono, or simply use `{ fetch(req: Request) => Response }` universal alternative format.
This PR adds Fetchable object format support for also `h3App[method]("route", <fetchable>)` and `defineHandler`. 
```js
import { H3 } from "h3";
const app = new H3();
app.get("/hello/:id", {
fetch: (req) => new Response("Standards FTW!"),
});
export default app;
```
This is particularly useful to be used together with filesystem routing like Nitro to mount any standard fetchable handler, also via filesystem routes.
```ts
// routes/hello/[id].ts
// Standard handler
import { defineHandler …
```
=> feat: support universal `{ fetch }` handlers

docs/2.utils/2.response.md, src/_deprecated.ts, src/index.ts, src/response.ts, src/utils/cors.ts, src/utils/proxy.ts, src/utils/response.ts, src/utils/static.ts, test/bench/bundle.test.ts, test/iterable.test.ts, test/status.test.ts, test/unit/package.test.ts, test/utils.test.ts
Constructing and returning a new `Response` can be costly and unnecessary. 
This PR introduces a new partial/pesudo response `HTTPResponse` (type-compat with `Response`) that is both exposed and used in internal utils. 
Breaking change: Utils below updated return a `HTTPResponse` also some won't (need to) have `event` as first param anymore*
- `html`*
- `iteratable`*
- `noContent`*
- `redirect`*
- `handleCors` 
- `proxy`
=> feat!: `HTTPResponse`

src/response.ts, test/app.test.ts, test/bench/bundle.test.ts
When there are both prepared headers (`event.res.headers.set`) and returning a new Response, we can override `res.headers` instead of cloning full request.
=> perf: try avoid cloning response for meriging headers
